#! /usr/bin/env python

import sys
from darkflow.cli import cliHandler

import tensorflow as tf

gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.7)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))


cliHandler(sys.argv)
